### ISSUE TITLE
What about the data enhancement result of LayoutLM+DINOv2+CLIP?

### ISSUE THREAD

**Issue by Richar-Du** [FudanNLPLAB/MouSi#1]
Thanks for your awesome work! I have a question about Section 3.4: Table 9 displays the data enhancement result in LayoutLM+ConvNeXt+CLIP. Why not perform this experiment on  LayoutLM+DINOv2+CLIP, since it is the best one among the triple vision experts? Thanks in advance.

**Comment by cnxupupup** [comment]
![eval](https://github.com/FudanNLPLAB/MouSi/assets/71219687/afe2f35c-ea93-4b5b-a416-c7b13d9781bd)
Thank you for your question. We have added the results of the LayoutLM+DINOv2+CLIP, the marks indicate that the results are from MMB/OpenCompass official, respectively. We'll update our arxiv later.

**Comment by Richar-Du** [comment]
Great! Thanks for your reply :)
